#!/usr/bin/ruby
require 'rubygems' 
require 'bundler/setup'
require "/Users/misha/Rails/RubyGrep/directory.rb"
require "/Users/misha/Rails/RubyGrep/file.rb"
require "/Users/misha/Rails/RubyGrep/line.rb"



directory = RubyGrep::Directory.new(ARGV[0], ARGV[1])
directory.print_files

# colorize
# izbavitsya ot vseh probelov
# sdelat' formatiroavanie